### ISSUE TITLE
Failed to Install the Fonts

### ISSUE THREAD

**Issue by tloriato** [GeekyAnts/NativeBase-Sketch-Template#9] opened 2017-06-14 17:35 UTC
Hey guys! I've been wanting to try this sketch for a while now, but just now I was able to.

Anyway, I installed ionicons with the `bower install ionicons` command and the SF Fonts through the .pkg downloaded, but I still got this error
<img width="455" alt="screen shot 2017-06-14 at 2 33 47 pm" src="https://user-images.githubusercontent.com/11580564/27146164-b8d574f0-510e-11e7-8cc3-4cfd4d919ac2.png">

Any ideas of what I might have done wrong?

**Comment by S-Kaushik** [comment] 2017-06-15 08:44
Hi Tiago,

This is unusual.
Can you try closing the template file and opening it again?

**Comment by tloriato** [comment] 2017-06-15 18:04
I tried, still got the problem. Maybe I installed the dependencies wrong?

**Comment by cmckni3** [comment] 2017-06-15 19:33
I had to download [Roboto](https://fonts.google.com/specimen/Roboto) as well.

Sketch still says I am missing `SFUIText-Semibold`, `SFUIText-Regular`, and `.SFNSText-Regular`.

**Comment by cmckni3** [comment] 2017-06-15 19:34
Installing XCode did not fix those missing fonts. It looks like the fonts are from iOS 9 and later. Not sure where to download them for macOS.

**Comment by cmckni3** [comment] 2017-06-16 23:01
I found out those fonts were removed from Sierra for some reason. They are absent from the [list of fonts included in Sierra](https://support.apple.com/en-us/HT206872).

I had to download the `SFUI` fonts from [here](https://github.com/ZTfer/weui-sketch/blob/master/font/SFUI.zip)

I am working on finding `SFNSText`. I think I might be able to copy them from El Capitan installer.

**Comment by cmckni3** [comment] 2017-06-16 23:02
Any chance of updating the sketch document to use fonts on Sierra or alternative fonts?

**Comment by tloriato** [comment] 2017-06-20 23:04
Any news guys?

**Comment by rudra077** [comment] 2017-06-21 06:31
Hi Chris,

This is unusual.
Actually we are using roboto and ionic text fonts in this Template.
and we are working to solve SF text warning.
if you are not able to install SF text then you can ignore SF text related warning because we are not using SF font in our Template.
you just click "open anyway" button and start using  NativeBase-Sketch-Template. @cmckni3 

Thank you.

**Comment by rudra077** [comment] 2017-06-21 06:43
Hi Tiago,

we are using roboto and ionic text fonts in this Template.
So make sure your system (Sketch app) have these fonts.
Roboto-https://fonts.google.com/specimen/Roboto
Ionic-http://ionicons.com/
and you can ignore  SF text warning or install.
SF-https://developer.apple.com/fonts/. @tloriato 

Thank you.

**Comment by SupriyaKalghatgi** [comment] 2017-07-24 06:32
@tloriato Did you get it running?

**Comment by tloriato** [comment] 2017-07-24 06:35
Sadly, no.

**Comment by S-Kaushik** [comment] 2017-07-24 09:41
@tloriato Are you still getting the same warning? If only SF Fonts are missing then you can `open anyway` because we haven't used them in the template.

**Comment by jimthedev** [comment] 2017-08-05 14:49
Can confirm, once you install Roboto and Ionicons you can pretty much ignore the rest because they aren't used.

**Comment by alexkuc** [comment] 2017-08-11 07:43
I have installed all the above fonts (confirmed via Font Book). However, I get this weird issue:

<img width="489" alt="screenshot 2017-08-11 15 38 44" src="https://user-images.githubusercontent.com/3331946/29204754-67d4859e-7eab-11e7-943a-0de5682d7a70.png">

I am on MacOS Sierra

**Comment by alexkuc** [comment] 2017-08-11 09:40
Found the culprit:

![screenshot 2017-08-11 17 31 57](https://user-images.githubusercontent.com/3331946/29208276-089f1cd6-7ebc-11e7-983f-4325cafb2f57.jpg)
Ps: the same is applicable to iOS layer

**Closed as completed** 2018-12-08 03:45 UTC
